new databases
LARP2023Z/LARPex pull request #58
Opened 2023-11-19 22:50 UTC by Reszkins

2023-11-19 23:58 UTC, iruszpel requested changes
Zmiany we wszystkich plikach? Zmieniłeś przypadkiem LF na CRLF?

2023-11-20 18:35 UTC, Reszkins commented
![repo](https://github.com/LARP2023Z/LARPex/assets/73691017/988ed614-408b-4ccf-9bbe-b869b492842b)
nie wiem co jest z tym repo ale nie da się zclonować normalnie, muszę robić git restore żeby mieć pliki z repo u siebie bo na start mam w git status, że wszystkie pliki są usunięte

dlatego jest tak jakby wszystkie pliki zostały zmienione, ale imo one są 1:1 takie jakie na mainie

jak chcecie to mergujcie a jak nie to trzeba repo naprawić, Daniel ma to samo, po http/ssh to samo

2023-11-20 18:50 UTC, closed without merging

2023-11-20 18:51 UTC, iruszpel commented
@Reszkins repo nie jest zepuste tylko Wy macie config gita, który automatycznie podmienia CRLF na LF i w plikach, które utworzył @ciszewsj  było CRLF (nie powinno być, wszyscy inni na froncie mamy LF i powinniśmy się trzymać jednego). [Tu macie więcej info](https://stackoverflow.com/a/20653073) o configu gita odnośnie tego. Prawdopodobnie macie `autocrlf = input`

2023-11-20 18:54 UTC, iruszpel commented
+ to, że nie możecie repo sklonować to dlatego, że jesteście na windowsie i folder o nazwie aux jest niedozwolony. [Tu info](https://help.interfaceware.com/v6/windows-reserved-file-names)

2023-11-20 19:25 UTC, ciszewsj commented
sory windown mi podmienił znowu :/